services:
  redis:
    container_name: redis
    image: "redis:8.2.1"
    ports:
      - "6379:6379"

  dynamodb:
    container_name: dynamodb
    image: "amazon/dynamodb-local:3.1.0"
    command: "-jar DynamoDBLocal.jar -inMemory"
    ports:
      - "8000:8000"
