version: "3.9"

services:
  redis:
    container_name: redis
    image: "redis/redis-stack:7.4.0-v3"
    ports:
      - "6379:6379"
      - "8001:8001"

  dynamodb:
    container_name: dynamodb
    image: "amazon/dynamodb-local:2.6.1"
    command: "-jar DynamoDBLocal.jar -inMemory"
    ports:
      - "8000:8000"
