openapi: 3.0.0

info:
  title: Age Verification API
  version: 1.0.0

tags:
  - name: site
    description: Site verifying its accounts.
  - name: avs
    description: Third-party age verification service.

paths:
  # site
  /verification-state:
    get:
      tags: [site]
      description: Gets the verification state for the account.
      operationId: getVerificationState
      responses:
        '200':
          description: Verification state for the account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationState'

  /verification-request/create:
    post:
      tags: [site]
      description: Creates a verification request for the account.
      operationId: createVerificationRequest
      responses:
        '200':
          description: Verification request for the account.
          content:
            application/json:
              schema:
                $ref: './age-certificate.yaml#/components/schemas/VerificationRequest'

  /age-certificate/process:
    post:
      tags: [site]
      description: Processes an age certificate from the age verification service.
      operationId: processAgeCertificate
      requestBody:
        description: Signed age certificate to process.
        content:
          application/json:
            schema:
              $ref: './age-certificate.yaml#/components/schemas/SignedAgeCertificate'
        required: true
      responses:
        '200':
          description: OK

  /site/{siteId}/verification-request/create:
    post:
      tags: [avs]
      description: Creates a verification request for the site.
      operationId: createVerificationRequestForSite
      parameters:
        - name: siteId
          description: ID of the site.
          in: path
          schema:
            type: string
          required: true
      requestBody:
        description: (optional) Data used by the age verification service to match the person to this request.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthMatchData'
      responses:
        '200':
          description: Verification request.
          content:
            application/json:
              schema:
                $ref: './age-certificate.yaml#/components/schemas/VerificationRequest'

  /verification-request/{requestId}/link:
    post:
      tags: [avs]
      description: Links the verification request to a user on the age verification service.
      operationId: linkVerificationRequestToUser
      parameters:
        - name: requestId
          description: ID of the verification request.
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK

  /verification-request/{requestId}/age-certificate/send:
    post:
      description: Sends an age certificate for the verification request.
      tags: [avs]
      operationId: sendAgeCertificateForVerificationRequest
      parameters:
        - name: requestId
          description: ID of the verification request.
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK

components:
  schemas:
    # site
    VerificationState:
      description: Current state of an account for age verification.
      type: object
      properties:
        status:
          description: Verification status.
          $ref: '#/components/schemas/VerificationStatus'
        user:
          description: Verified user if the account is verified.
          $ref: './age-certificate.yaml#/components/schemas/VerifiedUser'
        expiration:
          description: Time when an account's verified status expired or will expire.
          type: string
          format: date-time
      required: [status]

    VerificationStatus:
      description: Verification status of an account.
      type: string
      enum: [unverified, verified, expired]

    # avs
    AuthMatchData:
      description: Data used to check that the same person is using the site and the age verification service.
      properties:
        name:
          description: Name that determines how the freeform data is processed.
          type: string
        data:
          description: Freeform data.
          type: string
      required: [name, data]
