service:
  id: crackle
  verifiedAccountExpiresIn: P30D

clients:
  avs:
    url: http://localhost:9090
  dynamoDb:
    region: us-east-1
    testEndpointOverride: http://localhost:8000
  redis:
    url: http://localhost:6379

keys:
  signing:
    wX: 61340499596180719707288738669477306360190613239883629564918816825111167687915
    wY: 38000387743223524528339467703153930999010297887656121516318277573781881204945
  localization:
    key: NWKnDAiC7iM_hqothKM5Lnaor0xS77DzV9q9QpSeJLc

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors: []
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /dev/null
        archive: false

logging:
  appenders:
    - type: console
      threshold: off
