service:
  id: pop
  verifiedAccountExpiresIn: P30D

clients:
  avsUrl: http://localhost:9090

redis:
  url: http://localhost:6379

dynamoDb:
  region: us-east-1
  testEndpointOverride: http://localhost:8000

keys:
  signing:
    wX: 61340499596180719707288738669477306360190613239883629564918816825111167687915
    wY: 38000387743223524528339467703153930999010297887656121516318277573781881204945
  localization: DLVB7uFHVFKbepBuIfoUwmT6Nbi6dGytHzXLZX4YHK4

server:
  applicationConnectors:
    - type: http
      port: 8081
  adminConnectors: []
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /dev/null
        archive: false

logging:
  appenders:
    - type: console
      threshold: off
