services:
  redis:
    image: redis:${REDIS_TAG}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    depends_on:
      redis-seed:
        condition: service_completed_successfully

  redis-seed:
    image: alpine:${ALPINE_TAG}
    command: sh -c "cp -r /seed-data/* /data && chmod -R a+rw /data"
    volumes:
      - ./src/test/resources:/seed-data:ro
      - redis-data:/data

volumes:
  redis-data:
